### ISSUE TITLE
add other installed packages

### ISSUE THREAD

**Issue by ghost** [atom-community/autocomplete-snippets#10]
you can implement to load 'snippets' of other installed packages?

**Comment by jonathandelgado** [comment]
@joefitzgerald I would shoot in a PR, but I would literally replace the entire loading system with one line. 

`atom.config.get('snippets', {scope: atom.workspace.getActiveTextEditor().getLastCursor().getScopeDescriptor()})`

That grabs the snippets applicable for the current scope, including other packages.

Thoughts?
