### ISSUE TITLE
autocomplete snippets is stop working in 0.175 

### ISSUE THREAD

**Issue by yestoall** [atom-community/autocomplete-snippets#31]
any ideas what's wrong?

**Comment by ghyde** [comment]
I'm running version 0.177.0. Atom's Deprecation Cop states:

    atom.services is no longer available. To register service providers and consumers, use the providedServices and consumedServices fields in your package's package.json.
    Called 1 timeCreate Issue on autocomplete-snippets repo
        Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:64:11
        Object.activate - /Users/user/.atom/packages/autocomplete-snippets/lib/autocomplete-snippets.coffee:8:25

**Comment by joefitzgerald** [comment]
@ghyde that is unrelated to this issue.

@yestoall are you still experiencing this issue? Can you provide more information about your system, the version of atom you have installed, and the packages you have installed?

**Comment by yestoall** [comment]
no, it's working again with 1.76 & 1.77 
thanks for your work.
