### ISSUE TITLE
atom.service is deprecated

### ISSUE THREAD

**Issue by ghyde** [atom-community/autocomplete-snippets#33]
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:64:11)
Object.activate (/Users/user/.atom/packages/autocomplete-snippets/lib/autocomplete-snippets.coffee:8:25)
```

**Comment by joefitzgerald** [comment]
Yes, we're aware of this - see https://github.com/atom/atom#5277
