### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by hammackj** [atom-community/autocomplete-snippets#36]
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:64:11)
Object.activate (/Users/hammackj/.atom/packages/autocomplete-snippets/lib/autocomplete-snippets.coffee:8:25)
```

I am still getting this fully updated to atom 0.177.0 and snippets 1.0.0.

**Comment by joefitzgerald** [comment]
I had forgotten to actually release the new version of autocomplete-snippets. Update and restart, it'll be gone.
