### ISSUE TITLE
Fuzzy Completion

### ISSUE THREAD

**Issue by Sighter** [atom-community/autocomplete-snippets#40]
Hey guys. Thx for the nice work here.

I wanted to ask if is possible to add a fuzzy search for this completion. So i.e. if you have a snippet with the prefix "hello_something()" it also show up in the completion list if you type "some" or "thi"

Should this behavior maybe be a part of the autocomplete-plus package?

Cheers
Sascha

**Comment by benogle** [comment]
Closed by #49
