### ISSUE TITLE
Exact match should be on top of the list

### ISSUE THREAD

**Issue by JonGretar** [atom-community/autocomplete-snippets#43]
When writing javascript code a common snippet is `f` that expands into an anonymous function.
However if I type `f` the topmost and selected suggestion is `fix`. And the `f` snippet is number 6 in the list. If I was looking for `fix` I could add the letter 'i' to select that one however as `f` is the whole snippet trigger I am forced to press down 5 times to select it.

When returning the list of suggestions it should be sorted so it puts exact matches to the top.

**Comment by mjackson** [comment]
Just ran into this exact same issue myself. Thanks for the fix @JonGretar!

:+1:

**Comment by scottmessinger** [comment]
I ran into this as well! I used @JonGretar patch and it worked great. Thanks!

**Comment by benogle** [comment]
Closed by #49
