### ISSUE TITLE
Snippets with exact prefixes matches should appear first

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom-community/autocomplete-snippets#48]
For example, if the text before the cursor is `i`, a snippet with the prefix `i` (e.g. `it block` from language-coffee-script) should appear above a snippet with a longer prefix (e.g. `idea` from language-todo). Currently, the `idea` snippet is first.

**Comment by joefitzgerald** [comment]
:+1:

**Comment by joefitzgerald** [comment]
@maxbrunsfeld related: #47.

**Comment by joefitzgerald** [comment]
Duplicate of #43.
